name: book
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - scipy
  - slycot
  - control
  - sympy
  - tornado
  - jupyter-book
  - jupytext
  
  
